import {
  SUBSCRIPTION_VISIT_SUCCESS,
  GET_ALL_CLIENTS_SUCCESS,
  GET_MY_CLIENTS_SUCCESS,
  GET_USER_BY_ID_SUCCESS,
  GET_NOTES_AUTHOR_BY_ID_SUCCESS,
} from "../components/personal/constants";

export const KEYS = {
  [SUBSCRIPTION_VISIT_SUCCESS]: "user",
  [GET_ALL_CLIENTS_SUCCESS]: "clients",
  [GET_MY_CLIENTS_SUCCESS]: "clients",
  [GET_USER_BY_ID_SUCCESS]: "user",
  [GET_NOTES_AUTHOR_BY_ID_SUCCESS]: "author"
};
