import {
  SUBSCRIPTION_VISIT_SUCCESS,
  GET_ALL_CLIENTS_SUCCESS,
  GET_MY_CLIENTS_SUCCESS,
  GET_USER_BY_ID_SUCCESS,
  GET_NOTES_AUTHOR_BY_ID_SUCCESS,
  GET_ALL_TRAINERS_SUCCESS,
  GET_ALL_DOCTORS_SUCCESS,
  GET_ALL_MASSEURS_SUCCESS,
  GET_USERS_BY_ROLE_SUCCESS,
  GET_USER_SCHEDULE_BY_ID_SUCCESS,
  GET_STAFF_BOOKED_SESSION_SUCCESS,
  GET_STAFF_SCHEDULE_SUCCESS
} from "../components/personal/constants";

export const KEYS = {
  [SUBSCRIPTION_VISIT_SUCCESS]: "user",
  [GET_ALL_CLIENTS_SUCCESS]: "clients",
  [GET_MY_CLIENTS_SUCCESS]: "clients",
  [GET_USER_BY_ID_SUCCESS]: "user",
  [GET_NOTES_AUTHOR_BY_ID_SUCCESS]: "author",
  [GET_ALL_TRAINERS_SUCCESS]: "trainers",
  [GET_ALL_DOCTORS_SUCCESS]: "doctors",
  [GET_ALL_MASSEURS_SUCCESS]: "masseurs",
  [GET_USERS_BY_ROLE_SUCCESS]: "usersByRole",
  [GET_USER_SCHEDULE_BY_ID_SUCCESS]: "userSchedule",
  [GET_STAFF_BOOKED_SESSION_SUCCESS]: "userSchedule",
  [GET_STAFF_SCHEDULE_SUCCESS]: "staffSchedule"
};
